name: modis 

channels:
  - conda-forge

dependencies:
  - python
  - dask[complete]
  - jupyterlab
  - dask-labextension
  - jupyterlab-git
  - xarray
  - rioxarray
  - matplotlib 
  - h5netcdf
  - netcdf4
  - earthaccess
  - shapely
  - zarr
  - pystac-client
